#include <exception>
#include <stdexcept>

int main() {
  throw std::runtime_error("foo");
}
